### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luiswalter** [JOSM/turnlanes-tagging#26]
```
luis@luis-pc:~$ cd Desktop/
luis@luis-pc:~/Desktop$ java -jar josm-tested.jar 
INFO: Reassigning shortcut 'view:zoomselection' from null to 576 because of conflict with 3
INFO: Silent shortcut conflict: 'view:zoomselection' moved by 'AutoTools:CLAbuildings' to 'Alt+Shift+F1'.
INFO: loading plugin 'utilsplugin2' (version 32158)
INFO: loading plugin 'auto_tools' (version 1464287551)
INFO: Registered toolbar action without name: org.openstreetmap.josm.plugins.auto_tools.actions.MergeBuildingsAction
INFO: loading plugin 'turnlanes-tagging' (version 1465997942)
INFO: loading plugin 'buildings_tools' (version 32158)
INFO: Toolbar action without name: org.openstreetmap.josm.plugins.auto_tools.actions.MergeBuildingsAction
INFO: RemoteControl::Accepting remote connections on /127.0.0.1:8111
INFO: RemoteControl::Accepting remote connections on /0:0:0:0:0:0:0:1:8111
INFO: Message notifier active (checks every 5 minutes)
INFO: GET https://api.openstreetmap.org/api/0.6/user/details (get number of unread messages) -> 200 (585 B)
WARNING: Cannot start IPv4 remotecontrol https server on port 8112: Keystore was tampered with, or password was incorrect
WARNING: Cannot start IPv6 remotecontrol https server on port 8112: Keystore was tampered with, or password was incorrect
INFO: RemoteControl received: GET /load_and_zoom?left=-76.77246&bottom=39.18118&right=-76.75049&top=39.19821&changeset_comment=Add%20missing%20turn%20lanes%20from%20satellite%20imagery%20in%20Baltimore%20https%3A%2F%2Fgithub.com%2Fmapbox%2Fmapping%2Fissues%2F180&changeset_source=Bing HTTP/1.1
INFO: GET https://api.openstreetmap.org/api/0.6/map?bbox=-76.77246,39.18118,-76.75049,39.19821 -> 200
INFO: Reassigning shortcut 'mapmode:zoom' from null to 576 because of conflict with Z
INFO: Silent shortcut conflict: 'mapmode:zoom' moved by 'mapmode:SplittingTool' to 'Alt+Shift+F2'.
[INFO] CompositeCacheManager - Instance is null, returning unconfigured instance
[INFO] ThreadPoolManager - thread_pool.default PoolConfiguration = useBoundary = [false] boundarySize = [2000] maximumPoolSize = [150] minimumPoolSize = [4] keepAliveTime = [300000] whenBlockedPolicy = [RUN] startUpSize = [4]
[INFO] CompositeCacheManager - Setting default auxiliaries to null
[INFO] CompositeCacheManager - setting defaultCompositeCacheAttributes to [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 1000, maxSpoolPerRun = -1, diskUsagePattern = UPDATE, spoolChunkSize = 2 ]
[INFO] CompositeCacheManager - setting defaultElementAttributes to [ IS_LATERAL = true, IS_SPOOL = true, IS_REMOTE = true, IS_ETERNAL = false, MaxLifeSeconds = -1, IdleTime = -1, CreateTime = 1466016250949, LastAccessTime = 1466016250949, getTimeToLiveSeconds() = -1, createTime = 1466016250949 ]
[INFO] CompositeCacheConfigurator - Parsed regions []
[INFO] CompositeCacheManager - Finished configuration in 18 ms.
[INFO] CompositeCacheConfigurator - No special ElementAttribute class defined for key [jcs.region.TMS.elementattributes], using default class.
[INFO] AbstractDoubleLinkedListMemoryCache - initialized MemoryCache for TMS
[INFO] CompositeCache - Constructed cache with name [TMS] and cache attributes [ useLateral = true, useRemote = true, useDisk = true, maxObjs = 0, maxSpoolPerRun = -1, diskUsagePattern = UPDATE, spoolChunkSize = 2 ]
[INFO] IndexedDiskCache - Region [TMS] Cache file root directory: /home/luis/.josm/cache/tiles
[INFO] IndexedDiskCache - Region [TMS] Set maxKeySize to: '524288'
[INFO] IndexedDiskCache - Region [TMS] Loaded keys from [TMS], key count: 52123; up to 524288 will be available.
[INFO] IndexedDiskCache - Region [TMS] Finished inital consistency check, isOk = true in 54ms.
[INFO] IndexedDiskCache - Region [TMS] Indexed Disk Cache is alive.
ERROR: java.lang.NoSuchMethodError: org.openstreetmap.josm.gui.tagging.TagTable.getAddAction()Lorg/openstreetmap/josm/gui/tagging/TagTable$AddAction;
java.lang.NoSuchMethodError: org.openstreetmap.josm.gui.tagging.TagTable.getAddAction()Lorg/openstreetmap/josm/gui/tagging/TagTable$AddAction;
    at org.openstreetmap.josm.plugins.turnlanestagging.editor.TagEditor.buildButtonsPanel(TagEditor.java:31)
    at org.openstreetmap.josm.plugins.turnlanestagging.editor.TagEditor.buildTagEditorPanel(TagEditor.java:69)
    at org.openstreetmap.josm.plugins.turnlanestagging.editor.TagEditor.build(TagEditor.java:84)
    at org.openstreetmap.josm.plugins.turnlanestagging.editor.TagEditor.<init>(TagEditor.java:88)
    at org.openstreetmap.josm.plugins.turnlanestagging.TagEditorDialog.buildTagGridPanel(TagEditorDialog.java:112)
    at org.openstreetmap.josm.plugins.turnlanestagging.TagEditorDialog.build(TagEditorDialog.java:82)
    at org.openstreetmap.josm.plugins.turnlanestagging.TagEditorDialog.<init>(TagEditorDialog.java:48)
    at org.openstreetmap.josm.plugins.turnlanestagging.TagEditorDialog.getInstance(TagEditorDialog.java:53)
    at org.openstreetmap.josm.plugins.turnlanestagging.LaunchAction.launchEditor(LaunchAction.java:49)
    at org.openstreetmap.josm.plugins.turnlanestagging.LaunchAction.actionPerformed(LaunchAction.java:35)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Rub21** [comment]
@luiswalter  Debes usar una version de JOSM >1000 .
